on:
  workflow_dispatch:
  push:
    branches:
    - main
    - test-branch
    paths:
    - 'backend/cloudresume-challenge/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: validate SAM template
      run: |
        sam validate --template-file ./backend/cloudresume-challenge/template.yaml

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws region: eu-north-1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.14"

    - name: Install dependencies and run unit tests
      run: |
        pip install -r ./backend/cloudresume-challenge/hello_world/requirements.txt
        pip install pytest moto
        pytest ./backend/cloudresume-challenge/tests/unit

    - name: build and deploy SAM application
      run: |
        sam build --template-file backend/cloudresume-challenge/template.yaml
        sam deploy --template-file ./backend/cloudresume-challenge/template.yaml --stack-name cloudresume-stack --capabilities CAPABILITY_IAM --no-confirm-changeset --no-fail-on-empty-changeset
