on:
  workflow_dispatch:

  push:
    branches:
    - main
    - frontend-test
    paths:
    - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@
    - name: Authenticate to AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Sync frontend files to S3
      run: |
        aws s3 sync ./frontend s3://cloudwithjanet-resume-bkt --delete   

    - run: |+
        aws cloudfront create-invalidation --distribution-id ${{vars.CLOUDFRONT_DISTRIBUTION_ID}} --paths "/*"
            
